blank_issues_enabled: false
contact_links:
  - name: Telegram Group
    url: https://t.me/+Hfg0wmxzw_w1NGI0
    about: Questions asked in the group usually get answered faster.
  - name: IRC Channel
    url: https://kiwiirc.com/client/https://webchat.freenode.net//?nick=web-76|?##telebirr-telegram-bot
    about: In case you are unable to join our group due to Telegram restrictions, you can use our IRC channel
